-- MySQL Script generated by MySQL Workbench
-- Wed Mar 15 19:07:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`personal_visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personal_visit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `validity_period_from` DATE NOT NULL,
  `validity_period_for` DATE NOT NULL,
  `purpose_of_the_visit` VARCHAR(45) NOT NULL,
  `division` VARCHAR(45) NOT NULL,
  `FIO` VARCHAR(50) NOT NULL,
  `surname` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `patronymic` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(12) NULL,
  `email` VARCHAR(50) NOT NULL,
  `organization` VARCHAR(50) NULL,
  `note` VARCHAR(50) NOT NULL,
  `birthdate` DATE NOT NULL,
  `passport_series` VARCHAR(4) NOT NULL,
  `passport_number` VARCHAR(6) NOT NULL,
  `document_name` VARCHAR(64) NOT NULL,
  `document_unique_name` DATETIME NOT NULL,
  `photo` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`documents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL,
  `unique_name` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`photos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
